import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { PersonaAvatar } from "@/components/PersonaAvatar";
import { getPersonaByName } from "@/lib/personaConfig";
import { Badge } from "@/components/ui/badge";
import { useState } from "react";

interface DraftPreviewModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  draft: {
    id: string;
    channel: string;
    subject: string | null;
    message_body: string;
    persona_name?: string;
    invoice_number?: string;
  } | null;
  onApprove: (draftId: string) => Promise<void>;
  onEdit: (draftId: string, subject: string, body: string) => Promise<void>;
  onDiscard: (draftId: string) => Promise<void>;
  onRegenerate?: (draftId: string) => Promise<void>;
}

export const DraftPreviewModal = ({
  open,
  onOpenChange,
  draft,
  onApprove,
  onEdit,
  onDiscard,
  onRegenerate
}: DraftPreviewModalProps) => {
  const [isEditing, setIsEditing] = useState(false);
  const [editSubject, setEditSubject] = useState("");
  const [editBody, setEditBody] = useState("");
  const [processing, setProcessing] = useState(false);

  if (!draft) return null;

  const persona = draft.persona_name ? getPersonaByName(draft.persona_name) : null;

  const handleEdit = () => {
    setEditSubject(draft.subject || "");
    setEditBody(draft.message_body);
    setIsEditing(true);
  };

  const handleSaveEdit = async () => {
    setProcessing(true);
    try {
      await onEdit(draft.id, editSubject, editBody);
      setIsEditing(false);
      onOpenChange(false);
    } finally {
      setProcessing(false);
    }
  };

  const handleApprove = async () => {
    setProcessing(true);
    try {
      await onApprove(draft.id);
      onOpenChange(false);
    } finally {
      setProcessing(false);
    }
  };

  const handleDiscard = async () => {
    setProcessing(true);
    try {
      await onDiscard(draft.id);
      onOpenChange(false);
    } finally {
      setProcessing(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-3">
            {persona && <PersonaAvatar persona={persona} size="sm" />}
            <div>
              <div>AI Generated Draft</div>
              {draft.invoice_number && (
                <div className="text-sm font-normal text-muted-foreground">
                  Invoice #{draft.invoice_number}
                </div>
              )}
            </div>
          </DialogTitle>
          <DialogDescription>
            {persona && (
              <div className="flex items-center gap-2 mt-2">
                <span>Generated by <strong>{persona.name}</strong></span>
                <Badge variant="outline">{persona.tone}</Badge>
              </div>
            )}
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4">
          <div>
            <Label>Channel</Label>
            <Badge className="ml-2">{draft.channel.toUpperCase()}</Badge>
          </div>

          {draft.channel === "email" && (
            <div className="space-y-2">
              <Label htmlFor="subject">Subject</Label>
              {isEditing ? (
                <Input
                  id="subject"
                  value={editSubject}
                  onChange={(e) => setEditSubject(e.target.value)}
                />
              ) : (
                <div className="p-3 bg-muted rounded-md text-sm">
                  {draft.subject || "No subject"}
                </div>
              )}
            </div>
          )}

          <div className="space-y-2">
            <Label htmlFor="message">Message</Label>
            {isEditing ? (
              <Textarea
                id="message"
                value={editBody}
                onChange={(e) => setEditBody(e.target.value)}
                rows={10}
                className="font-mono text-sm"
              />
            ) : (
              <div className="p-4 bg-muted rounded-md text-sm whitespace-pre-wrap">
                {draft.message_body}
              </div>
            )}
          </div>
        </div>

        <DialogFooter className="flex-col sm:flex-row gap-2">
          {isEditing ? (
            <>
              <Button variant="outline" onClick={() => setIsEditing(false)} disabled={processing}>
                Cancel
              </Button>
              <Button onClick={handleSaveEdit} disabled={processing}>
                {processing ? "Saving..." : "Save Changes"}
              </Button>
            </>
          ) : (
            <>
              <Button variant="outline" onClick={handleDiscard} disabled={processing}>
                Discard
              </Button>
              <Button variant="outline" onClick={handleEdit} disabled={processing}>
                Edit
              </Button>
              {onRegenerate && (
                <Button variant="outline" onClick={() => onRegenerate(draft.id)} disabled={processing}>
                  Regenerate
                </Button>
              )}
              <Button onClick={handleApprove} disabled={processing}>
                {processing ? "Approving..." : "Approve & Send"}
              </Button>
            </>
          )}
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};
