// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-debtors.ts
import { createClient } from "npm:@supabase/supabase-js@^2.84.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.23.8";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_debtors_default = defineTool({
  name: "list_debtors",
  title: "List debtors",
  description: "List debtors (customer accounts) for the signed-in Recouply user, sorted by open balance descending.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(25).describe("Max debtors to return."),
    min_balance: z.number().min(0).default(0).describe("Only include debtors whose total_open_balance is at least this amount.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, min_balance }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await sb(ctx).from("debtors").select(
      "id, name, company_name, email, phone, total_open_balance, open_invoices_count, risk_tier, avg_days_to_pay, max_days_past_due"
    ).gte("total_open_balance", min_balance).eq("is_archived", false).order("total_open_balance", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { debtors: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-open-invoices.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.84.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.23.8";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_open_invoices_default = defineTool2({
  name: "list_open_invoices",
  title: "List open invoices",
  description: "List open (unpaid) invoices for the signed-in Recouply user. Filter by aging bucket or debtor. Sorted by days past due descending.",
  inputSchema: {
    limit: z2.number().int().min(1).max(200).default(50),
    debtor_id: z2.string().uuid().optional().describe("Restrict to a single debtor id."),
    aging_bucket: z2.enum(["current", "1-30", "31-60", "61-90", "91-120", "121+"]).optional().describe("Restrict to a single aging bucket.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, debtor_id, aging_bucket }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = sb2(ctx).from("invoices").select(
      "id, invoice_number, debtor_id, amount, balance, due_date, status, aging_bucket, days_past_due, currency"
    ).gt("balance", 0).order("days_past_due", { ascending: false }).limit(limit);
    if (debtor_id) q = q.eq("debtor_id", debtor_id);
    if (aging_bucket) q = q.eq("aging_bucket", aging_bucket);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { invoices: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-collection-tasks.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.84.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.23.8";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_collection_tasks_default = defineTool3({
  name: "list_collection_tasks",
  title: "List collection tasks",
  description: "List active collection tasks (Command Center kanban) for the signed-in Recouply user, filtered by status and priority.",
  inputSchema: {
    limit: z3.number().int().min(1).max(100).default(25),
    status: z3.enum(["open", "in_progress", "waiting", "completed"]).optional().describe("Filter by task status."),
    priority: z3.enum(["low", "medium", "high", "urgent"]).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status, priority }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = sb3(ctx).from("collection_tasks").select(
      "id, task_type, priority, status, summary, details, recommended_action, due_date, debtor_id, invoice_id, created_at"
    ).eq("is_archived", false).order("created_at", { ascending: false }).limit(limit);
    if (status) q = q.eq("status", status);
    if (priority) q = q.eq("priority", priority);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { tasks: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-debtor.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.84.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.23.8";
function sb4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_debtor_default = defineTool4({
  name: "get_debtor",
  title: "Get debtor",
  description: "Fetch full details for a single debtor (customer account), including balance, risk, and aging mix.",
  inputSchema: {
    debtor_id: z4.string().uuid().describe("The debtor's UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ debtor_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await sb4(ctx).from("debtors").select("*").eq("id", debtor_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Debtor not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { debtor: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "kguurazunazhhrhasahd";
var mcp_default = defineMcp({
  name: "recouply-mcp",
  title: "Recouply",
  version: "0.1.0",
  instructions: "Tools for Recouply, an AI-powered accounts receivable and collections platform. Use these tools to inspect debtors (customer accounts), open invoices, and active collection tasks for the signed-in user. All calls run under the user's row-level security, so results are scoped to their organization.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_debtors_default, list_open_invoices_default, list_collection_tasks_default, get_debtor_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
