// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-debtors.ts
import { createClient } from "npm:@supabase/supabase-js@^2.84.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.23.8";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_debtors_default = defineTool({
  name: "list_debtors",
  title: "List debtors",
  description: "List debtors (customer accounts) for the signed-in Recouply user, sorted by open balance descending.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(25).describe("Max debtors to return."),
    min_balance: z.number().min(0).default(0).describe("Only include debtors whose total_open_balance is at least this amount.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, min_balance }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await sb(ctx).from("debtors").select(
      "id, name, company_name, email, phone, total_open_balance, open_invoices_count, risk_tier, avg_days_to_pay, max_days_past_due"
    ).gte("total_open_balance", min_balance).eq("is_archived", false).order("total_open_balance", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { debtors: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-open-invoices.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.84.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.23.8";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var ACTIVE_STATUSES = ["Open", "PartiallyPaid", "InPaymentPlan", "Disputed", "FinalInternalCollections"];
var AGING_BUCKETS = {
  current: ["current"],
  "1-30": ["1-30", "dpd_1_30"],
  "31-60": ["31-60", "dpd_31_60"],
  "61-90": ["61-90", "dpd_61_90"],
  "91-120": ["91-120", "dpd_91_120"],
  "121+": ["121+", "dpd_121_150", "dpd_150_plus", "dpd_120_plus", "dpd_121_plus"]
};
function daysPastDue(dueDate) {
  if (!dueDate) return 0;
  const due = /* @__PURE__ */ new Date(`${dueDate}T00:00:00Z`);
  const today = /* @__PURE__ */ new Date();
  const todayUtc = Date.UTC(today.getUTCFullYear(), today.getUTCMonth(), today.getUTCDate());
  return Math.max(0, Math.floor((todayUtc - due.getTime()) / 864e5));
}
var list_open_invoices_default = defineTool2({
  name: "list_open_invoices",
  title: "List open invoices",
  description: "List open (unpaid) invoices for the signed-in Recouply user. Filter by aging bucket or debtor. Sorted by days past due descending.",
  inputSchema: {
    limit: z2.number().int().min(1).max(200).default(50),
    debtor_id: z2.string().uuid().optional().describe("Restrict to a single debtor id."),
    aging_bucket: z2.enum(["current", "1-30", "31-60", "61-90", "91-120", "121+"]).optional().describe("Restrict to a single aging bucket.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, debtor_id, aging_bucket }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = sb2(ctx).from("invoices").select(
      "id, reference_id, invoice_number, debtor_id, amount, amount_outstanding, due_date, issue_date, status, aging_bucket, currency, debtors(company_name, name, email)"
    ).in("status", ACTIVE_STATUSES).gt("amount_outstanding", 0).order("due_date", { ascending: true }).limit(limit);
    if (debtor_id) q = q.eq("debtor_id", debtor_id);
    if (aging_bucket) q = q.in("aging_bucket", AGING_BUCKETS[aging_bucket] ?? [aging_bucket]);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const invoices = (data ?? []).map((invoice) => ({
      ...invoice,
      balance: invoice.amount_outstanding ?? invoice.amount,
      days_past_due: daysPastDue(invoice.due_date),
      debtor_name: invoice.debtors?.company_name ?? invoice.debtors?.name ?? null
    })).sort((a, b) => b.days_past_due - a.days_past_due);
    return {
      content: [{ type: "text", text: JSON.stringify(invoices, null, 2) }],
      structuredContent: { invoices }
    };
  }
});

// src/lib/mcp/tools/list-collection-tasks.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.84.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.23.8";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_collection_tasks_default = defineTool3({
  name: "list_collection_tasks",
  title: "List collection tasks",
  description: "List active collection tasks (Command Center kanban) for the signed-in Recouply user, filtered by status and priority.",
  inputSchema: {
    limit: z3.number().int().min(1).max(100).default(25),
    status: z3.enum(["open", "in_progress", "waiting", "completed"]).optional().describe("Filter by task status."),
    priority: z3.enum(["low", "medium", "high", "urgent"]).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status, priority }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = sb3(ctx).from("collection_tasks").select(
      "id, task_type, priority, status, summary, details, recommended_action, due_date, debtor_id, invoice_id, created_at"
    ).eq("is_archived", false).order("created_at", { ascending: false }).limit(limit);
    if (status) q = q.eq("status", status);
    if (priority) q = q.eq("priority", priority);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { tasks: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-debtor.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.84.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.23.8";
function sb4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_debtor_default = defineTool4({
  name: "get_debtor",
  title: "Get debtor",
  description: "Fetch full details for a single debtor (customer account), including balance, risk, and aging mix.",
  inputSchema: {
    debtor_id: z4.string().uuid().describe("The debtor's UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ debtor_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await sb4(ctx).from("debtors").select("*").eq("id", debtor_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Debtor not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { debtor: data }
    };
  }
});

// src/lib/mcp/tools/list-contracts.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.84.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^3.23.8";
function sb5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_contracts_default = defineTool5({
  name: "list_contracts",
  title: "List contracts",
  description: "List contracts for the signed-in Recouply user. Optionally filter by status, contract type, or counterparty name. Sorted by expiry date ascending (soonest first).",
  inputSchema: {
    limit: z5.number().int().min(1).max(100).default(25),
    status: z5.string().optional().describe("Filter by contract status (e.g. active, expired, draft)."),
    contract_type: z5.string().optional().describe("Filter by contract type."),
    counterparty: z5.string().optional().describe("Case-insensitive match on counterparty name.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status, contract_type, counterparty }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = sb5(ctx).from("contracts").select(
      "id, title, contract_type, status, counterparty_name, counterparty_email, contract_value, currency, effective_date, expiry_date, renewal_date, ai_summary, created_at"
    ).order("expiry_date", { ascending: true, nullsFirst: false }).limit(limit);
    if (status) q = q.eq("status", status);
    if (contract_type) q = q.eq("contract_type", contract_type);
    if (counterparty) q = q.ilike("counterparty_name", `%${counterparty}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { contracts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-contract.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.84.0";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z6 } from "npm:zod@^3.23.8";
function sb6(ctx) {
  return createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_contract_default = defineTool6({
  name: "get_contract",
  title: "Get contract",
  description: "Get a single contract by id, including AI summary, extracted terms, key dates, risk flags, and critical dates for the signed-in user.",
  inputSchema: {
    contract_id: z6.string().uuid().describe("The contract id.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ contract_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const client = sb6(ctx);
    const { data: contract, error } = await client.from("contracts").select("*").eq("id", contract_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!contract) return { content: [{ type: "text", text: "Contract not found" }], isError: true };
    const [riskFlags, criticalDates] = await Promise.all([
      client.from("contract_risk_flags").select("*").eq("contract_id", contract_id),
      client.from("contract_critical_dates").select("*").eq("contract_id", contract_id).order("date", { ascending: true })
    ]);
    const payload = {
      contract,
      risk_flags: riskFlags.data ?? [],
      critical_dates: criticalDates.data ?? []
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "kguurazunazhhrhasahd";
var mcp_default = defineMcp({
  name: "recouply-mcp",
  title: "Recouply",
  version: "0.1.0",
  instructions: "Tools for Recouply, an AI-powered accounts receivable and collections platform. Use these tools to inspect debtors (customer accounts), open invoices, active collection tasks, and contracts (with AI summaries, key dates, and risk flags) for the signed-in user. All calls run under the user's row-level security, so results are scoped to their organization.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_debtors_default, list_open_invoices_default, list_collection_tasks_default, get_debtor_default, list_contracts_default, get_contract_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
